FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++ libc6-compat

COPY package*.json ./
RUN npm install --include=dev
RUN echo "NODE_ENV is $NODE_ENV"

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
